
dw SFX_Script_00_A, SFX_Script_00_B
dw SFX_Script_01_A, SFX_Script_01_B
dw SFX_Script_02_A, $0000
dw SFX_Script_03_A, SFX_Script_03_B
dw SFX_Script_04_A, $0000
dw SFX_Script_05_A, SFX_Script_05_B
dw SFX_Script_06_A, SFX_Script_06_B
dw SFX_Script_07_A, SFX_Script_07_B
dw SFX_Script_08_A, SFX_Script_08_B
dw SFX_Script_09_A, SFX_Script_09_B
dw SFX_Script_0A_A, SFX_Script_0A_B
dw SFX_Script_0B_A, $0000
dw SFX_Script_0C_A, SFX_Script_0C_B
dw SFX_Script_0D_A, SFX_Script_0D_B
dw SFX_Script_0E_A, SFX_Script_0E_B
dw SFX_Script_0F_A, SFX_Script_0F_B
dw SFX_Script_10_A, SFX_Script_10_B
dw SFX_Script_11_A, SFX_Script_11_B
dw SFX_Script_12_A, SFX_Script_12_B
dw SFX_Script_13_A, SFX_Script_13_B
dw SFX_Script_14_A, SFX_Script_14_B
dw SFX_Script_15_A, SFX_Script_15_B
dw SFX_Script_16_A, SFX_Script_16_B
dw SFX_Script_17_A, SFX_Script_17_B
dw SFX_Script_18_A, SFX_Script_18_B
dw SFX_Script_19_A, SFX_Script_19_B
dw SFX_Script_1A_A, SFX_Script_1A_B
dw SFX_Script_1B_A, SFX_Script_1B_B
dw SFX_Script_1C_A, SFX_Script_1C_B
dw SFX_Script_1D_A, SFX_Script_1D_B
dw SFX_Script_1E_A, SFX_Script_1E_B
dw SFX_Script_1F_A, SFX_Script_1F_B
dw SFX_Script_20_A, SFX_Script_20_B
dw SFX_Script_21_A, SFX_Script_21_B
dw SFX_Script_22_A, SFX_Script_22_B
dw SFX_Script_23_A, SFX_Script_23_B
dw SFX_Script_24_A, SFX_Script_24_B
dw SFX_Script_25_A, SFX_Script_25_B
dw SFX_Script_26_A, SFX_Script_26_B
dw SFX_Script_27_A, SFX_Script_27_B
dw SFX_Script_28_A, $0000
dw SFX_Script_29_A, SFX_Script_29_B
dw SFX_Script_2A_A, SFX_Script_2A_B
dw SFX_Script_2B_A, SFX_Script_2B_B
dw SFX_Script_2C_A, SFX_Script_2C_B
dw SFX_Script_2D_A, SFX_Script_2D_B
dw SFX_Script_2E_A, SFX_Script_2E_B
dw SFX_Script_2F_A, SFX_Script_2F_B
dw SFX_Script_30_A, SFX_Script_30_B
dw SFX_Script_31_A, SFX_Script_31_B
dw SFX_Script_32_A, SFX_Script_32_B
dw SFX_Script_33_A, $0000
dw SFX_Script_34_A, SFX_Script_34_B
dw SFX_Script_35_A, SFX_Script_35_B
dw SFX_Script_36_A, $0000
dw SFX_Script_37_A, SFX_Script_37_B
dw SFX_Script_38_A, SFX_Script_38_B
dw SFX_Script_39_A, SFX_Script_39_B
dw SFX_Script_3A_A, SFX_Script_3A_B
dw SFX_Script_3B_A, SFX_Script_3B_B
dw SFX_Script_3C_A, SFX_Script_3C_B
dw SFX_Script_3D_A, SFX_Script_3D_B
dw SFX_Script_3E_A, SFX_Script_3E_B
dw SFX_Script_3F_A, SFX_Script_3F_B
dw SFX_Script_40_A, SFX_Script_40_B
dw SFX_Script_41_A, SFX_Script_41_B
dw SFX_Script_42_A, SFX_Script_42_B
dw SFX_Script_43_A, SFX_Script_43_B
dw SFX_Script_44_A, SFX_Script_44_B
dw SFX_Script_45_A, SFX_Script_45_B
dw SFX_Script_46_A, SFX_Script_46_B
dw SFX_Script_47_A, SFX_Script_47_B
dw SFX_Script_48_A, SFX_Script_48_B
dw SFX_Script_49_A, SFX_Script_49_B
dw SFX_Script_4A_A, SFX_Script_4A_B
dw SFX_Script_4B_A, SFX_Script_4B_B
dw SFX_Script_4C_A, SFX_Script_4C_B
dw SFX_Script_4D_A, SFX_Script_4D_B
dw SFX_Script_4E_A, SFX_Script_4E_B
dw SFX_Script_4F_A, SFX_Script_4F_B
dw SFX_Script_50_A, SFX_Script_50_B
dw SFX_Script_51_A, SFX_Script_51_B
dw SFX_Script_52_A, SFX_Script_52_B
dw SFX_Script_53_A, SFX_Script_53_B
dw SFX_Script_54_A, SFX_Script_54_B
dw SFX_Script_55_A, SFX_Script_55_B
dw SFX_Script_56_A, $0000
dw SFX_Script_57_A, SFX_Script_57_B
dw SFX_Script_58_A, SFX_Script_58_B
dw SFX_Script_59_A, SFX_Script_59_B
dw SFX_Script_5A_A, SFX_Script_5A_B
dw SFX_Script_5B_A, SFX_Script_5B_B
dw SFX_Script_5C_A, SFX_Script_5C_B
dw SFX_Script_5D_A, SFX_Script_5D_B
dw SFX_Script_5E_A, SFX_Script_5E_B
dw SFX_Script_5F_A, SFX_Script_5F_B
dw SFX_Script_60_A, $0000
dw SFX_Script_61_A, SFX_Script_61_B
dw SFX_Script_62_A, SFX_Script_62_B
dw SFX_Script_63_A, SFX_Script_63_B
dw SFX_Script_64_A, SFX_Script_64_B
dw SFX_Script_65_A, SFX_Script_65_B
dw SFX_Script_66_A, SFX_Script_66_B
dw SFX_Script_67_A, SFX_Script_67_B
dw SFX_Script_68_A, SFX_Script_68_B
dw SFX_Script_69_A, SFX_Script_69_B
dw SFX_Script_6A_A, SFX_Script_6A_B
dw SFX_Script_6B_A, SFX_Script_6B_B
dw SFX_Script_6C_A, SFX_Script_6C_B
dw SFX_Script_6D_A, SFX_Script_6D_B
dw SFX_Script_6E_A, $0000
dw SFX_Script_6F_A, SFX_Script_6F_B
dw SFX_Script_70_A, SFX_Script_70_B
dw SFX_Script_71_A, SFX_Script_71_B
dw SFX_Script_72_A, SFX_Script_72_B
dw SFX_Script_73_A, SFX_Script_73_B
dw SFX_Script_74_A, SFX_Script_74_B
dw SFX_Script_75_A, $0000
dw SFX_Script_76_A, SFX_Script_76_B
dw SFX_Script_77_A, SFX_Script_77_B
dw SFX_Script_78_A, SFX_Script_78_B
dw SFX_Script_79_A, SFX_Script_79_B
dw SFX_Script_7A_A, SFX_Script_7A_B
dw SFX_Script_7B_A, SFX_Script_7B_B
dw SFX_Script_7C_A, SFX_Script_7C_B
dw SFX_Script_7D_A, SFX_Script_7D_B
dw SFX_Script_7E_A, SFX_Script_7E_B
dw SFX_Script_7F_A, SFX_Script_7F_B
dw SFX_Script_80_A, SFX_Script_80_B
dw SFX_Script_81_A, SFX_Script_81_B
dw SFX_Script_82_A, SFX_Script_82_B
dw SFX_Script_83_A, SFX_Script_83_B
dw SFX_Script_84_A, SFX_Script_84_B
dw SFX_Script_85_A, SFX_Script_85_B
dw SFX_Script_86_A, SFX_Script_86_B
dw SFX_Script_87_A, SFX_Script_87_B
dw SFX_Script_88_A, SFX_Script_88_B
dw SFX_Script_89_A, SFX_Script_89_B
dw SFX_Script_8A_A, SFX_Script_8A_B
dw SFX_Script_8B_A, SFX_Script_8B_B
dw SFX_Script_8C_A, SFX_Script_8C_B
dw SFX_Script_8D_A, SFX_Script_8D_B
dw SFX_Script_8E_A, SFX_Script_8E_B
dw SFX_Script_8F_A, SFX_Script_8F_B
dw SFX_Script_90_A, SFX_Script_90_B
dw SFX_Script_91_A, SFX_Script_91_B
dw SFX_Script_92_A, SFX_Script_92_B
dw SFX_Script_93_A, SFX_Script_93_B
dw SFX_Script_94_A, SFX_Script_94_B
dw SFX_Script_95_A, SFX_Script_95_B
dw SFX_Script_96_A, SFX_Script_96_B
dw SFX_Script_97_A, SFX_Script_97_B
dw SFX_Script_98_A, SFX_Script_98_B
dw SFX_Script_99_A, SFX_Script_99_B
dw SFX_Script_9A_A, $0000
dw SFX_Script_9B_A, $0000
dw SFX_Script_9C_A, SFX_Script_9C_B
dw SFX_Script_9D_A, SFX_Script_9D_B
dw SFX_Script_9E_A, SFX_Script_9E_B
dw SFX_Script_9F_A, SFX_Script_9F_B
dw SFX_Script_A0_A, SFX_Script_A0_B
dw SFX_Script_A1_A, SFX_Script_A1_B
dw SFX_Script_A2_A, SFX_Script_A2_B
dw SFX_Script_A3_A, SFX_Script_A3_B
dw SFX_Script_A4_A, SFX_Script_A4_B
dw SFX_Script_A5_A, SFX_Script_A5_B
dw SFX_Script_A6_A, SFX_Script_A6_B
dw SFX_Script_A7_A, $0000
dw SFX_Script_A8_A, SFX_Script_A8_B
dw SFX_Script_A9_A, SFX_Script_A9_B
dw SFX_Script_AA_A, SFX_Script_AA_B
dw SFX_Script_AB_A, SFX_Script_AB_B
dw SFX_Script_AC_A, SFX_Script_AC_B
dw SFX_Script_AD_A, SFX_Script_AD_B
dw SFX_Script_AE_A, SFX_Script_AE_B
dw SFX_Script_AF_A, $0000
dw $0000, SFX_Script_B0_B
dw SFX_Script_B1_A, SFX_Script_B1_B
dw SFX_Script_B2_A, SFX_Script_B2_B
dw SFX_Script_B3_A, SFX_Script_B3_B
dw SFX_Script_B4_A, SFX_Script_B4_B
dw SFX_Script_B5_A, SFX_Script_B5_B
dw SFX_Script_B6_A, SFX_Script_B6_B
dw SFX_Script_B7_A, SFX_Script_B7_B
dw SFX_Script_B8_A, SFX_Script_B8_B
dw SFX_Script_B9_A, SFX_Script_B9_B
dw SFX_Script_BA_A, SFX_Script_BA_B
dw SFX_Script_BB_A, $0000
dw SFX_Script_BC_A, $0000
dw SFX_Script_BD_A, SFX_Script_BD_B
dw SFX_Script_BE_A, SFX_Script_BE_B
dw SFX_Script_BF_A, SFX_Script_BF_B
dw SFX_Script_C0_A, SFX_Script_C0_B
dw SFX_Script_C1_A, SFX_Script_C1_B
dw SFX_Script_C2_A, SFX_Script_C2_B
dw SFX_Script_C3_A, SFX_Script_C3_B
dw SFX_Script_C4_A, SFX_Script_C4_B
dw SFX_Script_C5_A, SFX_Script_C5_B
dw SFX_Script_C6_A, SFX_Script_C6_B
dw SFX_Script_C7_A, SFX_Script_C7_B
dw SFX_Script_C8_A, $0000
dw SFX_Script_C9_A, SFX_Script_C9_B
dw SFX_Script_CA_A, SFX_Script_CA_B
dw SFX_Script_CB_A, SFX_Script_CB_B
dw SFX_Script_CC_A, SFX_Script_CC_B
dw SFX_Script_CD_A, SFX_Script_CD_B
dw SFX_Script_CE_A, $0000
dw SFX_Script_CF_A, SFX_Script_CF_B
dw SFX_Script_D0_A, SFX_Script_D0_B
dw SFX_Script_D1_A, SFX_Script_D1_B
dw SFX_Script_D2_A, SFX_Script_D2_B
dw SFX_Script_D3_A, SFX_Script_D3_B
dw SFX_Script_D4_A, SFX_Script_D4_B
dw SFX_Script_D5_A, SFX_Script_D5_B
dw SFX_Script_D6_A, SFX_Script_D6_B
dw $0000, SFX_Script_D7_B
dw SFX_Script_D8_A, SFX_Script_D8_B
dw SFX_Script_D9_A, SFX_Script_D9_B
dw SFX_Script_DA_A, SFX_Script_DA_B
dw SFX_Script_DB_A, SFX_Script_DB_B
dw SFX_Script_DC_A, SFX_Script_DC_B
dw SFX_Script_DD_A, SFX_Script_DD_B
dw SFX_Script_DE_A, SFX_Script_DE_B
dw SFX_Script_DF_A, SFX_Script_DF_B
dw SFX_Script_E0_A, SFX_Script_E0_B
dw SFX_Script_E1_A, SFX_Script_E1_B
dw SFX_Script_E2_A, SFX_Script_E2_B
dw SFX_Script_E3_A, SFX_Script_E3_B
dw SFX_Script_E4_A, SFX_Script_E4_B
dw SFX_Script_E5_A, SFX_Script_E5_B
dw SFX_Script_E6_A, SFX_Script_E6_B
dw SFX_Script_E7_A, $0000
dw SFX_Script_E8_A, SFX_Script_E8_B
dw SFX_Script_E9_A, SFX_Script_E9_B
dw SFX_Script_EA_A, $0000
dw SFX_Script_EB_A, SFX_Script_EB_B
dw SFX_Script_EC_A, SFX_Script_EC_B
dw SFX_Script_ED_A, SFX_Script_ED_B
dw SFX_Script_EE_A, $0000
dw SFX_Script_EF_A, SFX_Script_EF_B
dw SFX_Script_F0_A, SFX_Script_F0_B
dw SFX_Script_F1_A, SFX_Script_F1_B
dw SFX_Script_F2_A, SFX_Script_F2_B
dw SFX_Script_F3_A, SFX_Script_F3_B
dw $0000, SFX_Script_F4_B
dw SFX_Script_F5_A, SFX_Script_F5_B
dw SFX_Script_F6_A, SFX_Script_F6_B
dw SFX_Script_F7_A, $0000
dw SFX_Script_F8_A, SFX_Script_F8_B
dw SFX_Script_F9_A, SFX_Script_F9_B
dw SFX_Script_FA_A, $0000
dw SFX_Script_FB_A, SFX_Script_FB_B
dw SFX_Script_FC_A, SFX_Script_FC_B
dw $0000, $0000
dw $0000, $0000
dw $0000, $0000
